[PHP]
extension_dir = "C:\Users\phlspxuser\scoop\apps\php\current\ext"
extension = curl
extension = fileinfo
extension = mbstring
extension = openssl
extension = pdo_pgsql
extension = pdo_sqlite
extension = pgsql
extension = sodium
extension = sqlite3
extension = zip

curl.cainfo = "C:\Users\phlspxuser\OneDrive\development\tools\cacert.pem"
openssl.cafile = "C:\Users\phlspxuser\OneDrive\development\tools\cacert.pem"

date.timezone = Asia/Manila
memory_limit = 256M
max_execution_time = 120
display_errors = On
error_reporting = E_ALL
zend.exception_ignore_args = Off

extension=intl
extension_dir = "ext"
