create table if not exists public.intraday_dispatch (
  id bigint generated by default as identity primary key,
  dispatch_date date not null,
  hour smallint not null check (hour between 0 and 23),
  order_qty numeric not null default 0 check (order_qty >= 0),
  synced_at timestamptz not null default now(),
  unique (dispatch_date, hour)
);

create index if not exists intraday_dispatch_date_hour_idx
  on public.intraday_dispatch (dispatch_date, hour);

alter table public.intraday_dispatch enable row level security;

drop policy if exists intraday_dispatch_authenticated_read on public.intraday_dispatch;
create policy intraday_dispatch_authenticated_read
  on public.intraday_dispatch
  for select
  to authenticated
  using (true);
